# Site
repository: chrisatrotter/my-resume
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Christopher A. Trotter
title: Software Engineer
email: chrisatrotters@gmail.com
website: https://chrisatrotter.github.io/my-resume/

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: chrisatrotter
github_username:  chrisatrotter
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: chrisatrotter
linkedin_username: chrisatrotters
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: chrisatrotters
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Christpher and I'm a passionate software engineer with interests in event-driven architecture, functional programming, stream processing and concurrency theory.
  I recently graduated with a master in computer science, where the focus of the study was to interpret concurrency as higher-dimensional objects using formal methods such as category theory, formal verification, model checking, and algebraic topology.
  As part of the journey, I learned fundamental concepts of concurrency theory, programming languages, event-based vs. state-based models and application of category theory within a functional programming paradigm.
  
  I am focused on putting my passion and skills to good use by supporting organizations and projects with their difficult engineering problems. 

content:
  #- title: Projects # Title for the section
  #  layout: list # Type of content section (list/text)
  #  content:
  #    - layout: top-middle
  #      title: PUBG GraphQL server
  #      link: github.com/megacat-studio/pubg-graphql-api
  #      # link_text: Project Website
  #      additional_links:
  #        - title:  megacat-studio/pubg-graphql-api
  #          icon: fab fa-github
  #          url: github.com/megacat-studio/pubg-graphql-api
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #      quote: >
  #        This is probably one of the greatest API's ever created, if you don't agree you're probably wrong.
  #      description: | # this will include new lines to allow paragraphs
  #        I started this project as a way if learning <mark>GraphQL</mark> and <mark>Typescript</mark> it has since grown into a fully fledged API. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Sparebank 1
        link: sparebank1.no
        # link_text: boringcompany.com
        sub_title: IT Consultant
        caption: November 2016 - Jan 2019
        quote: >
          A Norwegian alliance of independent banks that helps their customers simplify their everyday finance.
        description: | # this will include new lines to allow paragraphs
          Every bank needs transactions to be properly administered and Sparebank1 is no exception. Managing high volume transactions is hard and I played my part by monitoring to ensure safe transactions for our customers.
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Oslo
        caption: 2016 - 2018
        sub_title: MSc Computer Science
        quote: >
          Established in 1811, UiO is the oldest higher education institution in Norway, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in the Nordic countries.
        description: | # this will include new lines to allow paragraphs
          The Master's program deals with system development, programming, data communication, distributed systems and information security.
          With a Master's Degree in Informatics - Programming and Networks, One can understand the totality of such systems and the theories on which they are based. One can help develop and maintain such systems, and one has in-depth knowledge of the areas of the program.
      - layout: left
        title: University of Oslo
        caption: 2013 - 2016
        sub_title: BSc Computer Science
        quote: >
          Established in 1811, UiO is the oldest higher education institution in Norway, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in the Nordic countries.
        description: | # this will include new lines to allow paragraphs
          During my time at UiO I learnt most of my key skills that I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

  
  - title: Publication # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Sculptures in Concurrency
        caption: Dec 2018
        sub_title: Computer Science - Concurrency
        quote: >
          - Uli Fahrenberg - Ecole Polytechnique, Palaiseau, France
          - Christian Johansen - Institute of Informatics, University of Oslo, Norway
          - Christopher Trotter - Institute of Informatics, University of Oslo, Norway
          - Krzysztof Ziemianski - Institute of Mathematics, University of Warsaw
        description: | # this will include new lines to allow paragraphs
          We give a formalization of Pratt’s intuitive sculpting process for higherdimensional automata (HDA). Based on this, we show that sculptures, Pratt’s Chu spaces, and Johansen’s ST-structures are in close correspondence. We also develop an algorithm to decide whether a HDA can be sculpted and use this to show that some natural acyclic HDA are not sculptures. We believe that our result shed new light on the intuitions behind sculpting as a method of modeling concurrent behavior, showing the precise reaches of its expressiveness. We also show that there are sculptures whose unfoldings cannot be sculpted, and that sculptures are the same as Euclidean cubical complexes. This exposes a close connection between geometric and combinatorial models for concurrency which may be of use for both areas.
          
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in computer science some of my other interests and hobbies are:
      - Calisthenics
      - Gaming
      - Bartender
      - Barista
      - Mentoring

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
